In [ ]:
from tensorflow.keras.preprocessing import image

In [ ]:
img=image.load_img('/content/10002.jpg',target_size=(224,224))

In [ ]:
img_array=image.img_to_array(img)
img_array

array([[[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       ...,

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 2

In [ ]:
img_array.shape

(224, 224, 3)

In [ ]:
import numpy as np
expanded_img_array=np.expand_dims(img_array,axis=0)
print(expanded_img_array.shape)

(1, 224, 224, 3)


In [ ]:
expanded_img_array

array([[[[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        ...,

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
       

In [ ]:
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input

In [ ]:
import tensorflow
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D

In [ ]:
model = ResNet50(weights='imagenet',include_top=False,input_shape=(224,224,3))
model.trainable = False

model = tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()
])

In [ ]:
preprocessed_img=preprocess_input(expanded_img_array)
print(preprocessed_img.shape)
preprocessed_img

(1, 224, 224, 3)


array([[[[47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         ...,
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007]],

        [[47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         ...,
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007]],

        [[47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         ...,
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007]],

        ...,

        [[47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         [47.122   , 21.442009,  7.640007],
         ...,


In [ ]:
model.predict(preprocessed_img)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step


array([[ 0.        , 11.603235  ,  0.31419814, ...,  4.6112747 ,
         0.        , 17.991728  ]], dtype=float32)

In [ ]:
model.predict(preprocessed_img).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step


(1, 2048)

In [ ]:
model.predict(preprocessed_img).flatten().shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step


(2048,)

In [ ]:
model.predict(preprocessed_img)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step


array([[ 0.        , 11.603235  ,  0.31419814, ...,  4.6112747 ,
         0.        , 17.991728  ]], dtype=float32)

In [ ]:
import numpy as np

# Assuming preprocessed_img is the input image you want to predict on
predictions = model.predict(preprocessed_img).flatten()
normalized_predictions = predictions / np.linalg.norm(predictions)




1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step


In [42]:
import numpy as np

# Make sure to import numpy if you haven't already
model.predict(preprocessed_img).flatten() / np.linalg.norm(model.predict(preprocessed_img).flatten())


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step


array([0.        , 0.04111336, 0.00111329, ..., 0.01633898, 0.        ,
       0.06374949], dtype=float32)

In [43]:
from numpy .linalg import norm
norm(model.predict(preprocessed_img).flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step


282.22543

In [44]:
np.sqrt(np.dot (model.predict(preprocessed_img).flatten(),model.predict(preprocessed_img).flatten()))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step


282.22543